# Generated by Django 5.1.1 on 2024-09-11 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organizer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("email", models.EmailField(max_length=256)),
                ("phone", models.CharField(max_length=256)),
                ("address", models.CharField(blank=True, max_length=256, null=True)),
                ("website", models.URLField(blank=True, max_length=256, null=True)),
                ("registrationdate", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=256)),
                ("maxcapacity", models.IntegerField()),
                (
                    "ticketprice",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("concert", "Concert"),
                            ("conference", "Conference"),
                            ("sport", "Sport"),
                            ("social", "Social"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("preparation", "Preparation"),
                            ("canceled", "Canceled"),
                        ],
                        default="active",
                        max_length=64,
                    ),
                ),
                ("startdate", models.DateTimeField()),
                ("enddate", models.DateTimeField()),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="Events.organizer",
                    ),
                ),
            ],
        ),
    ]
